#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Jan  4 16:25:35 2020

@author: dev
"""

"""
A script to open a random radiochannel
"""

import os
import random

DATA_FOLDER = r"/Users/Dev/Documents/MeetPi/Data/chunks/"

os.chdir(DATA_FOLDER)
 #   print ("You are in", folder)
files = os.listdir(DATA_FOLDER)
testresultfile = open('/Users/Dev/Documents/MeetPi/testfile.txt','w') 
 
for i in range (1,100):
    angle = random.randint(0,360)
    random_file = random.choice(files)
    filedetails = random_file.split("_")
#    print (filedetails)
#    os.system ("afplay " + random_file)
#    testresultfile.write("Act Angle," + angle + ",Est. Angle," + angle + ",Age," + filedetails[1] + ",Act Sex," + filedetails[0] + ",Est Sex," + filedetails[0] + ",Act Time," + filedetails[2] + ",Est Time," + filedetails[2] ) 
    testresultfile.write("{},{},{},{}\n".format(angle,filedetails[1],filedetails[0],filedetails[2]) )